### PR TITLE
DM-31447: update cycle 24-compatible code for ts_rotator_controller 1.5.0 prototype

### PR DESCRIPTION
**Pull request by r-owen**

### CODE REVIEW

**Comment by r-owen** [comment]
The pr-head Jenkins build will fail because it attempts to use salobj 7, etc.

**Review by teweitsai — APPROVED** [review]
Looks good. Thanks for the quick update! Please note that Tekniker might need to update the Simulink model again for the inconsistency of rotator position. Thanks!

**Comment by tribeiro** [comment]
you could pin the versions of ts_salobj and ts_idl on the conda recipe so the build would pass..

e.g.: https://github.com/lsst-ts/ts_scheduler/blob/1ac308749201c70097198705c3a1ba23406a979d/conda/meta.yaml#L16-L18

**Comment by r-owen** [comment]
Please feel free to make further updates to the telemetry message format. It is very easy to accommodate those in the CSC (as long as we don't lose anything the CSC relies on, with no good replacement. But that seems unlikely).

**Pull request merged**
